### ISSUE TITLE
Add a changelog using scriv

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/cookiecutter-tutor-plugin#20]
Example to follow: https://github.com/overhangio/tutor-ecommerce/pull/39

**Comment by kdmccormick** [comment]
@regisb in addition to having a changelog to this repo, do you think that we should add changelog management to newly generated plugins?

**Comment by regisb** [comment]
Now that's a bigger question. I think that we should avoid doing that, because I'd rather not make such technical decisions for 3rd-party plugin maintainers. For that same reason, I would rather not add CI scripts to the cookiecutter templates.

That being said, those same reasons do not apply to official plugins -- those in the ["main"](https://github.com/overhangio/tpi#main) index. We should definitely make sure that these plugins conform to the changelog template. And they should also have valid CI scripts, include a LICENSE file, a description of who is the right maintainer, etc. Right now with just a dozen or so repos we can make do with manual commands and relying on maintainers. But that model is now showing its limits. One of the items on my todo-list is to watch again Jeremy's ["Herding Ponies"](https://www.youtube.com/watch?v=ny-3AaNHbbs) talk. There are certainly lessons to be drawn here on how to manage many repositories simultaneously.

**Comment by arbrandes** [comment]
See comment [in the PR](https://github.com/overhangio/cookiecutter-tutor-plugin/pull/22#issuecomment-1584728769): the question at the moment is if we should have a changelog here at all, since we're not doing releases.

**Comment by CodeWithEmad** [comment]
@kdmccormick if no one is working on this, I would love to open a PR.

**Comment by kdmccormick** [comment]
Whoops, we discussed this here, https://github.com/overhangio/cookiecutter-tutor-plugin/pull/22#issuecomment-1710428516 and resolved it via http://github.com/overhangio/cookiecutter-tutor-plugin/pull/24. I should have closed this, that's my bad.
