### ISSUE TITLE
Error "Unable to create file '.github/workflows/test.yml' Error message: 'matrix' is undefined" when creating a new plugin

### ISSUE THREAD

**Issue by angonz** [overhangio/cookiecutter-tutor-plugin#32]
I get an error when trying to create a plugin:
```
Unable to create file '.github/workflows/test.yml'
Error message: 'matrix' is undefined
```

Maybe cookiecutter is mistaking the curly brackets in [.github/workflows/test.yml](https://github.com/overhangio/cookiecutter-tutor-plugin/blob/500c4d29ece886b358a68417d933bf774b517c7d/%7B%7B%20cookiecutter.package_name%20%7D%7D/.github/workflows/test.yml#L15)?

It's curious that I'm setting `[12/12] Include continuous integration files for GitHub CI (y/n) (y): n` and yet it tries to create the workflow file.

**Comment by CodeWithEmad** [comment]
Thanks for the heads up. I totally forgot to run the tests before creating the previous PR. 
The problem is the curly braces indeed. I'll fix it in a minute.
cookie-cutter will create the template based on the input details first, then the clean-up part comes in [post_gen](https://github.com/overhangio/cookiecutter-tutor-plugin/blob/master/hooks/post_gen_project.py) hook.

**Comment by CodeWithEmad** [comment]
@angonz kindly check and let me know if there's any further issues with the cookiecutter.

**Comment by angonz** [comment]
Works!! Thanks for your support
